-- Controle de Consignados

-- Versão Original

SELECT  

SNK_GET_CUSTO('MEDIOSEMICMS',ITE.CODEMP,ITE.CODPROD,ITE.CODLOCALORIG,ITE.CONTROLE,SYSDATE) * (ITE.QTDNEG-ITE.QTDENTREGUE) AS CUSTO_TOTAL_REAL, 
CASE WHEN CAB.CODTIPOPER = 1410 
AND NVL((   SELECT 
            MAX(I.NUNOTARET) 
            FROM AD_PENDFAT P 
            INNER JOIN AD_ITENSPED I ON P.CODPEND = I.CODPEND
            WHERE P.NUNOTAEST = ITE.NUNOTA
            AND I.SEQUENCIA = ITE.AD_SEQUENCIAPEND AND EXISTS (SELECT * FROM TGFITE WHERE NUNOTA = I.NUNOTARET)
        ),0) = 0 
        THEN 
        'S'
        WHEN CAB.CODTIPOPER <> 1410 THEN
        ITE.PENDENTE
        ELSE 'N'
        END
         AS "Pendente",

ITE.TERCEIROS As "Terceiros",
CUS.CODCENCUS,
CUS.DESCRCENCUS As "Centro_Resultado",
CAB.CODTIPOPER AS "Codigo_da_TOP",
CASE WHEN CAB.CODTIPOPER = 781 THEN 
(SELECT
LISTAGG(TO_CHAR(VAR.NUNOTAORIG)||' - ' ||CAB.DTNEG||' - ' ||CASE WHEN CAB.AD_DTUTILIZACAO IS NULL THEN ' ' ELSE TO_CHAR(CAB.AD_DTUTILIZACAO,'DD/MM/YYYY') END,'/ ') WITHIN GROUP (ORDER BY VAR.NUNOTA) AS NUNOTA 

FROM TGFVAR VAR 
INNER JOIN (SELECT ITENS.NUNOTA,ITENS.SEQUENCIA,ITENS.CODPROD FROM TGFITE ITENS)PP 
ON PP.NUNOTA = VAR.NUNOTA AND PP.SEQUENCIA=VAR.SEQUENCIA
WHERE VAR.NUNOTA = CAB.NUNOTA
AND VAR.SEQUENCIA = ITE.SEQUENCIA
GROUP BY VAR.NUNOTA) END AS PEDIDO_ORIG,
TPO.DESCROPER As "Descricao_da_TOP", 
CAB.NUMNOTA As "Nro_Nota",
CAB.NUNOTA As "Nro_Unico",
CAB.DTNEG As "DtNegoc", 
UFS.UF AS "UF_Parceiro",
CAB.CODPARC As "CodParceiro",
DEST.CODPARC AS "CodParceiro_Fat",
DEST.NOMEPARC AS "Nome_do_Parceiro_Fat",
PAR.NOMEPARC As "Nome_do_Parceiro",
ITE.CODLOCALORIG As "CodLocal",
LOC.DESCRLOCAL As "Descricao_do_Local",
ITE.CODPROD As "CodProduto",
PRO.DESCRPROD As "DescProdutos",
PRO.REFFORN AS "Ref_Fornecedor",
PRO.COMPLDESC AS "Prod_Complemento",
ITE.CONTROLE As "Controle",
ITE.QTDNEG As "Qtd_Itens", 
ITE.QTDENTREGUE As "Qtde_Entregue", 
ITE.QTDNEG-ITE.QTDENTREGUE As "Qtd_Pendente_2",
CASE ITE.PENDENTE WHEN 'S' THEN 'Sim' ELSE 'Não' END ITEPENDENTE,
(ITE.QTDNEG-ITE.QTDENTREGUE)*ITE.VLRUNIT As "Valor_Pendente",
(ITE.QTDNEG-ITE.QTDENTREGUE)*  SNK_GET_CUSTO('GERENCIAL',ITE.CODEMP,ITE.CODPROD,ITE.CODLOCALORIG,ITE.CONTROLE,CAB.DTENTSAI) AS "Vlr_Custo_Total",
CASE WHEN  CAB.PENDENTE = 'N' THEN CAB.DTALTER END AS DT_ALTERACAO,
CASE WHEN  CAB.PENDENTE = 'N' THEN (SELECT NOMEUSU FROM TSIUSU WHERE CODUSU = CAB.CODUSU) END AS USU_ALTERACAO,
ITE.VLRUNIT As "Valor_Item", ITE.VLRTOT *  (CASE WHEN CAB.TIPMOV='D' THEN -1 ELSE 1 END ) As "Vlr_Total_Itens_Pedido",
 SNK_GET_CUSTO('GERENCIAL',ITE.CODEMP,ITE.CODPROD,ITE.CODLOCALORIG,ITE.CONTROLE,CAB.DTENTSAI)  As "Valor_do_Custo",
SNK_GET_CUSTO('MEDIOSEMICMS',ITE.CODEMP,ITE.CODPROD,ITE.CODLOCALORIG,ITE.CONTROLE,CAB.DTENTSAI)  As "Valor_do_Custo_Sem_ICMS", --- oito LINHAS ABAIXO INSERIDAS LUIZ PORTO
CASE WHEN CAB.CODTIPOPER IN (781,881) THEN (SELECT ((DIN.ALIQUOTA)/100)*ITE.VLRTOT FROM TGFDIN DIN WHERE DIN.CODIMP = 6 AND DIN.NUNOTA = CAB.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA) END  as "PIS",
CASE WHEN CAB.CODTIPOPER IN (781,881) THEN (SELECT DIN.ALIQUOTA FROM TGFDIN DIN WHERE DIN.CODIMP = 6 AND DIN.NUNOTA = CAB.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA) END AS "AL_PIS",
CASE WHEN CAB.CODTIPOPER IN (781,881) THEN (SELECT ((DIN.ALIQUOTA)/100)*ITE.VLRTOT FROM TGFDIN DIN WHERE DIN.CODIMP = 7 AND DIN.NUNOTA = CAB.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA) END  "COFINS",
CASE WHEN CAB.CODTIPOPER IN (781,881) THEN (SELECT DIN.ALIQUOTA FROM TGFDIN DIN WHERE DIN.CODIMP = 7 AND DIN.NUNOTA = CAB.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA) END AS "AL_COFINS",
CASE WHEN CAB.CODTIPOPER IN (781,881) THEN (SELECT (IMA.ALIQUOTA/100)*ITE.VLRTOT FROM TGFIMA IMA WHERE IMA.CODIMP = 3 AND IMA.CODIGO = 1) END as "CSLL",
CASE WHEN CAB.CODTIPOPER IN (781,881) THEN (SELECT IMA.ALIQUOTA FROM TGFIMA IMA WHERE IMA.CODIMP = 3 AND IMA.CODIGO = 1) END AS "AL_CSLL",
CASE WHEN CAB.CODTIPOPER IN (781,881) THEN (SELECT (IMA.ALIQUOTA/100)*ITE.VLRTOT FROM TGFIMA IMA WHERE IMA.CODIMP = 4 AND IMA.CODIGO = 1) END as "IRPJ",
CASE WHEN CAB.CODTIPOPER IN (781,881) THEN (SELECT IMA.ALIQUOTA FROM TGFIMA IMA WHERE IMA.CODIMP = 4 AND IMA.CODIGO = 1) END AS "AL_IRPJ",
CAB.OBSERVACAO As "Observacao_da_Nota" ,
CAB.AD_MEDICO_TEX  || ' '||MED.NOMEMEDICO  AS "Medico",
CAB.AD_PACIENTE as "Paciente",
CAB.AD_CONVENIO_TEX || ' '|| CON.NOME as "Convenio",
UF.UF AS "UF_Parc_Orig",
CAB.CODPARCDEST AS "Codigo_Parc_Orig",
EST.DTVAL AS VALIDADE,
(SELECT NOMEPARC FROM TGFPAR WHERE CODPARC = CAB.CODPARCDEST ) AS "Parceiro_Orig",
CAB.AD_DTUTILIZACAO AS "DT_Utilizacao",
VEN.APELIDO,

(SELECT  LISTAGG( TO_CHAR(DTVENC,'DD/MM/YYYY'), '; ')
         WITHIN GROUP (ORDER BY NUFIN) FROM TGFFIN WHERE NUNOTA = CAB.NUNOTA) AS VENCIMENTO,
         
PRO.MARCA as MARCA,
PRO.AD_LINHA as LINHA,
PROCED.CODPROCED as "CodProcedimento",
PROCED.DESCRPROCED as "Procedimento"

FROM TGFCAB CAB

INNER JOIN TGFITE ITE ON (CAB.NUNOTA=ITE.NUNOTA)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC=PAR.CODPARC)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TPO ON (CAB.CODTIPOPER=TPO.CODTIPOPER AND CAB.DHTIPOPER=TPO.DHALTER)
INNER JOIN TSIEMP EMP ON (ITE.CODEMP=EMP.CODEMP)
INNER JOIN TGFLOC LOC ON (ITE.CODLOCALORIG=LOC.CODLOCAL)
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC

LEFT JOIN AD_PENDFAT FAT ON CAB.AD_CODPEND = FAT.CODPEND

LEFT JOIN TGFPAR DEST  ON CAB.CODPARCDEST = DEST.CODPARC
LEFT JOIN TSICID CID ON PAR.CODCID = CID.CODCID 
LEFT JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
LEFT JOIN TSICID CIDD ON DEST.CODCID = CIDD.CODCID
LEFT JOIN TSIUFS UF ON CIDD.UF = UF.CODUF 
LEFT JOIN TSICUS CUS ON CAB.CODCENCUS = CUS.CODCENCUS
LEFT JOIN AD_TIPOPROCED PROCED ON FAT.CODPROCED  = PROCED.CODPROCED
LEFT JOIN AD_CONVENIO CON ON CAB.AD_CODCONVENIO = CON.CODCONVENIO 
LEFT JOIN AD_MEDICO MED ON CAB.AD_CODMEDICO = MED.CODMEDICO
LEFT JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
LEFT JOIN TGFEST EST ON (CAB.CODEMP = EST.CODEMP AND ITE.CODPROD = EST.CODPROD AND ITE.CONTROLE = EST.CONTROLE AND ITE.CODLOCALORIG = EST.CODLOCAL AND EST.TIPO = 'P' AND EST.CODPARC = 0)

WHERE 
    (:P_PACIENTE IS NULL OR  CAB.AD_PACIENTE   LIKE '%' || UPPER(:P_PACIENTE) || '%' )
AND ( :P_CONVENIO IS NULL OR  CAB.AD_CONVENIO_TEX   LIKE '%' || UPPER(:P_CONVENIO) || '%' )
AND (:P_PARCEIRO IS NULL OR CAB.CODPARC = :P_PARCEIRO)
AND ( CAB.CODCENCUS IN :P_CR)
AND ( CAB.CODTIPOPER IN :P_TOP)
AND (:P_LOTE IS NULL OR  UPPER(ITE.CONTROLE) LIKE '%' || UPPER(:P_LOTE ) || '%' )
AND (:P_PRODUTO IS NULL OR :P_PRODUTO = ITE.CODPROD)
AND (:P_PERIODO.INI IS NULL OR TRUNC(CAB.AD_DTUTILIZACAO) >= :P_PERIODO.INI)   
AND (:P_PERIODO.FIN IS NULL OR TRUNC(CAB.AD_DTUTILIZACAO) <= :P_PERIODO.FIN) 
AND (:P_PERIODONEG.INI IS NULL OR TRUNC(CAB.DTNEG) >= :P_PERIODONEG.INI)   
AND (:P_PERIODONEG.FIN IS NULL OR TRUNC(CAB.DTNEG) <= :P_PERIODONEG.FIN)
AND CASE WHEN CAB.CODTIPOPER = 1410 
        AND NVL((   SELECT 
            MAX(NUNOTARET) 
            FROM AD_PENDFAT P 
            INNER JOIN AD_ITENSPED I ON P.CODPEND = I.CODPEND
            WHERE P.NUNOTAEST = ITE.NUNOTA
            AND I.SEQUENCIA = ITE.AD_SEQUENCIAPEND
        ),0) = 0 
        THEN 
        'S'
        WHEN CAB.CODTIPOPER <> 1410 THEN
        ITE.PENDENTE
        ELSE 'N'
        END IN :P_PENDENTE
AND  (CAB.CODTIPOPER = 1410 OR CAB.STATUSNOTA = 'L')
AND  ITE.SEQUENCIA >0






-- Versão alterada

SELECT  

CASE WHEN CAB.CODTIPOPER = 1410 
AND NVL((   SELECT 
            MAX(I.NUNOTARET) 
            FROM AD_PENDFAT P 
            INNER JOIN AD_ITENSPED I ON P.CODPEND = I.CODPEND
            WHERE P.NUNOTAEST = ITE.NUNOTA
            AND I.SEQUENCIA = ITE.AD_SEQUENCIAPEND AND EXISTS (SELECT * FROM TGFITE WHERE NUNOTA = I.NUNOTARET)
        ),0) = 0 
        THEN 
        'S'
        WHEN CAB.CODTIPOPER <> 1410 THEN
        ITE.PENDENTE
        ELSE 'N'
        END
         AS "Pendente",

ITE.TERCEIROS As "Terceiros",
CUS.CODCENCUS,
CUS.DESCRCENCUS As "Centro_Resultado",
CAB.CODTIPOPER AS "Codigo_da_TOP",

TPO.DESCROPER As "Descricao_da_TOP", 
CAB.NUMNOTA As "Nro_Nota",
CAB.NUNOTA As "Nro_Unico",
CAB.DTNEG As "DtNegoc", 
UFS.UF AS "UF_Parceiro",
CAB.CODPARC As "CodParceiro",
DEST.CODPARC AS "CodParceiro_Fat",
DEST.NOMEPARC AS "Nome_do_Parceiro_Fat",
PAR.NOMEPARC As "Nome_do_Parceiro",
ITE.CODLOCALORIG As "CodLocal",
LOC.DESCRLOCAL As "Descricao_do_Local",
ITE.CODPROD As "CodProduto",
PRO.DESCRPROD As "DescProdutos",
PRO.REFFORN AS "Ref_Fornecedor",
PRO.COMPLDESC AS "Prod_Complemento",
ITE.CONTROLE As "Controle",
ITE.QTDNEG As "Qtd_Itens", 
ITE.QTDENTREGUE As "Qtde_Entregue", 
ITE.QTDNEG-ITE.QTDENTREGUE As "Qtd_Pendente_2",
(ITE.QTDNEG-ITE.QTDENTREGUE)*ITE.VLRUNIT As "Valor_Pendente",
(ITE.QTDNEG-ITE.QTDENTREGUE)*  SNK_GET_CUSTO('GERENCIAL',ITE.CODEMP,ITE.CODPROD,ITE.CODLOCALORIG,ITE.CONTROLE,CAB.DTENTSAI) AS "Vlr_Custo_Total",
ITE.VLRUNIT As "Valor_Item", ITE.VLRTOT *  (CASE WHEN CAB.TIPMOV='D' THEN -1 ELSE 1 END ) As "Vlr_Total_Itens_Pedido",
 SNK_GET_CUSTO('GERENCIAL',ITE.CODEMP,ITE.CODPROD,ITE.CODLOCALORIG,ITE.CONTROLE,CAB.DTENTSAI)  As "Valor_do_Custo",
SNK_GET_CUSTO('MEDIOSEMICMS',ITE.CODEMP,ITE.CODPROD,ITE.CODLOCALORIG,ITE.CONTROLE,CAB.DTENTSAI)  As "Valor_do_Custo_Sem_ICMS", --- oito LINHAS ABAIXO INSERIDAS LUIZ PORTO * Removidas em 09/12/2024, se tratavam das colunas dos impostos
CAB.AD_MEDICO_TEX  || ' '||MED.NOMEMEDICO  AS "Medico",
CAB.AD_PACIENTE as "Paciente",
CAB.AD_CONVENIO_TEX || ' '|| CON.NOME as "Convenio",
UF.UF AS "UF_Parc_Orig",
CAB.CODPARCDEST AS "Codigo_Parc_Orig",
EST.DTVAL AS VALIDADE,
(SELECT NOMEPARC FROM TGFPAR WHERE CODPARC = CAB.CODPARCDEST ) AS "Parceiro_Orig",
CAB.AD_DTUTILIZACAO AS "DT_Utilizacao",
VEN.APELIDO,
PRO.AD_LINHA as LINHA,
PROCED.CODPROCED as "CodProcedimento",
PROCED.DESCRPROCED as "Procedimento"

FROM TGFCAB CAB

INNER JOIN TGFITE ITE ON (CAB.NUNOTA=ITE.NUNOTA)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC=PAR.CODPARC)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TPO ON (CAB.CODTIPOPER=TPO.CODTIPOPER AND CAB.DHTIPOPER=TPO.DHALTER)
INNER JOIN TSIEMP EMP ON (ITE.CODEMP=EMP.CODEMP)
INNER JOIN TGFLOC LOC ON (ITE.CODLOCALORIG=LOC.CODLOCAL)
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC

LEFT JOIN AD_PENDFAT FAT ON CAB.AD_CODPEND = FAT.CODPEND

LEFT JOIN TGFPAR DEST  ON CAB.CODPARCDEST = DEST.CODPARC
LEFT JOIN TSICID CID ON PAR.CODCID = CID.CODCID 
LEFT JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
LEFT JOIN TSICID CIDD ON DEST.CODCID = CIDD.CODCID
LEFT JOIN TSIUFS UF ON CIDD.UF = UF.CODUF 
LEFT JOIN TSICUS CUS ON CAB.CODCENCUS = CUS.CODCENCUS
LEFT JOIN AD_TIPOPROCED PROCED ON FAT.CODPROCED  = PROCED.CODPROCED
LEFT JOIN AD_CONVENIO CON ON CAB.AD_CODCONVENIO = CON.CODCONVENIO 
LEFT JOIN AD_MEDICO MED ON CAB.AD_CODMEDICO = MED.CODMEDICO
LEFT JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
LEFT JOIN TGFEST EST ON (CAB.CODEMP = EST.CODEMP AND ITE.CODPROD = EST.CODPROD AND ITE.CONTROLE = EST.CONTROLE AND ITE.CODLOCALORIG = EST.CODLOCAL AND EST.TIPO = 'P' AND EST.CODPARC = 0)

WHERE 
    (:P_PACIENTE IS NULL OR  CAB.AD_PACIENTE   LIKE '%' || UPPER(:P_PACIENTE) || '%' )
AND ( :P_CONVENIO IS NULL OR  CAB.AD_CONVENIO_TEX   LIKE '%' || UPPER(:P_CONVENIO) || '%' )
AND (:P_PARCEIRO IS NULL OR CAB.CODPARC = :P_PARCEIRO)
AND ( CAB.CODCENCUS IN :P_CR)
AND ( CAB.CODTIPOPER IN :P_TOP)
AND (:P_LOTE IS NULL OR  UPPER(ITE.CONTROLE) LIKE '%' || UPPER(:P_LOTE ) || '%' )
AND (:P_PRODUTO IS NULL OR :P_PRODUTO = ITE.CODPROD)
AND (:P_PERIODO.INI IS NULL OR TRUNC(CAB.AD_DTUTILIZACAO) >= :P_PERIODO.INI)   
AND (:P_PERIODO.FIN IS NULL OR TRUNC(CAB.AD_DTUTILIZACAO) <= :P_PERIODO.FIN) 
AND (:P_PERIODONEG.INI IS NULL OR TRUNC(CAB.DTNEG) >= :P_PERIODONEG.INI)   
AND (:P_PERIODONEG.FIN IS NULL OR TRUNC(CAB.DTNEG) <= :P_PERIODONEG.FIN)
AND CASE WHEN CAB.CODTIPOPER = 1410 
        AND NVL((   SELECT 
            MAX(NUNOTARET) 
            FROM AD_PENDFAT P 
            INNER JOIN AD_ITENSPED I ON P.CODPEND = I.CODPEND
            WHERE P.NUNOTAEST = ITE.NUNOTA
            AND I.SEQUENCIA = ITE.AD_SEQUENCIAPEND
        ),0) = 0 
        THEN 
        'S'
        WHEN CAB.CODTIPOPER <> 1410 THEN
        ITE.PENDENTE
        ELSE 'N'
        END IN :P_PENDENTE
AND  (CAB.CODTIPOPER = 1410 OR CAB.STATUSNOTA = 'L')
AND  ITE.SEQUENCIA >0